Feature/update dependencies
toggle-corp/fujs pull request #35
Opened 2021-12-29 10:33 UTC by tnagorra

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests

2021-12-30 08:18 UTC, samshara approved these changes

2021-12-30 09:48 UTC, AdityaKhatri requested changes

2021-12-30 09:48 UTC, AdityaKhatri commented on mydocs/README.md
> +[![Install Size](https://packagephobia.now.sh/badge?p=@togglecorp/fujs)](https://packagephobia.now.sh/result?p=@togglecorp/fujs@1.9.2-beta.0) [![Build Status](https://travis-ci.com/toggle-corp/fujs.s
The docs was generated before the package was published and hence has an outdated version id.

2022-01-04 06:27 UTC, AdityaKhatri approved these changes

2022-01-04 06:28 UTC, merged